"""Add keywords to BlogPost

Revision ID: 37347d4a6444
Revises: 6b6bf642e760
Create Date: 2024-06-06 09:31:54.729285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37347d4a6444'
down_revision = '6b6bf642e760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keywords', sa.String(length=200), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=140),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=140),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('keywords')

    # ### end Alembic commands ###
